### ISSUE TITLE
Using dos2unix in Dockerfile in github download ....

### ISSUE THREAD

**Issue by hooch21** [bobby-didcoding/drf_course#10]
According to the link, when you clone from Github to a Windows machine, Windows git is set up to automatically convert EOL characters to CRLF, even if the original was created on Linux. 

"I hadn't consider this as a potential problem since the files were freshly cloned from Github and were originally created on Linux. What I didn't know is that on Windows Git is set up to automatically convert EOL characters to CRLF."

One solution, is to use VS Code to change the CRLF to LF using the 'select end of line sequence' in the bottom right status bar. 

However, I think a better solution is to use dos2unix in the Docker file. 
Below is a Dockerfile which uses dos2unix. I want to point out that in order to get the dos2unix command to RUN correctly, I had to copy the entrypoint.sh file from ./backend/docker/entrypoints/ folder to the root folder (/) on the linux machine. And then change the ENTRYPOINT to ["/entrypoint.sh"]. 

In order to get the dos2unix command to work, the entry point had to be located at the root level in linux. 

FROM python:3.10

ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1

RUN set -e; \
    apt-get update ;\
    apt-get -y install netcat ;\
    apt-get -y install gettext ; \
    apt-get -y install dos2unix ;

COPY ./docker/entrypoints/entrypoint.sh  /

RUN set -e; \
    dos2unix /entrypoint.sh ; \
    chmod +w /entrypoint.sh ;

RUN mkdir /code
COPY . /code/
WORKDIR /code

RUN set -e; \
    /usr/local/bin/python -m pip install --upgrade pip ;\
    python -m pip install -r /code/requirements.txt ;

EXPOSE 8000
ENTRYPOINT ["/entrypoint.sh"]

https://itecnote.com/tecnote/windows-building-docker-images-on-windows-entrypoint-script-no-such-file-or-directory/

**Comment by bobby-didcoding** [comment]
This is great, thanks.

I tend to avoid using entrypoint files these days as they don't work on some machines due to local git settings etc.

These days I use Dockerise and run commands in the docker-compose file.

Dockerfile example:

FROM python:3.10

### 1. Set environment variables
ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1
ENV DOCKERIZE_VERSION v0.6.1


### 2. Setup GDAL
RUN apt-get update &&\
    apt-get -y install gettext ;\
    apt-get -y  install httpie; \
    apt-get install -y binutils libproj-dev gdal-bin python3-gdal

### 3. Add dockerize to allow waiting for the DB to load.
RUN wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && tar -C /usr/local/bin -xzvf dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && rm dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz

RUN mkdir /code
COPY . /code/
WORKDIR /code

RUN set -e; \
    /usr/local/bin/python -m pip install --upgrade pip ;\
    python -m pip install --default-timeout=100 -r /code/requirements/dev.txt ;

EXPOSE 8000

Docker-compose example:

version: '3.8'

services:
  postgres:
    image: kartoza/postgis:13.0
    # image: postgres
    restart: unless-stopped
    volumes:
      - pg:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
      - POSTGRES_DB=dev
      - POSTGRES_PORT= 5432
    ports:
      - "5432:5432"


  app:
    build:
      context: ../app/backend
      dockerfile: docker/docker_files/Dockerfile
    restart: unless-stopped
    command: >
      bash -c "dockerize -wait tcp://postgres:5432
      && python manage.py makemigrations
      && python manage.py migrate
      && python manage.py runserver 0.0.0.0:8080 --settings=project.conf.dev
      && python manage.py test"
    volumes:
      - ../app/backend:/code
    ports:
      - 8000:8000
    env_file:
      - ../.env
    depends_on:
      - postgres

Works like a charm on all machines I've used :)
